M48
; DRILL file {KiCad 7.0.7} date 2023 October 16, Monday 23:42:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-16T23:42:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X2.5179Y-5.1986
X4.4179Y-5.1986
T2
X3.201Y-2.6868
X3.201Y-4.8719
X5.101Y-2.6868
X5.101Y-4.8719
T0
M30
